### ISSUE TITLE
weighted_mean_trimmed fails on non-sorted data of size 2

### ISSUE THREAD

**Issue by r-suzuki** [tobiasschoch/robsurvey#1]
It seems that `weighted_mean_trimmed` fails if `length(x) = 2` and `x` is not sorted in ascending order:
```r
> robsurvey::weighted_mean_trimmed(1:2, c(1, 1))
[1] 1.5
> robsurvey::weighted_mean_trimmed(2:1, c(1, 1))
[1] NA
Warning message:
Division by zero
```

Here's the session info;
```r
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1 tools_4.2.1    robsurvey_0.5 
```

Last but not least, thanks for sharing a nice package!

**Comment by tobiasschoch** [comment]
Yes, indeed! Thanks for pointing this out.

My first experiments indicate that `weighted_quantile()` is not correct for samples of size n = 2 that are sorted in descending order. As a consequence, the trimmed mean is not correct for such samples. For samples of size n>2, it seems to be fine.

I will investigate the problem in more detail next weekend.

**Comment by tobiasschoch** [comment]
The weighted quantile (other than the median) as computed by the C function `wquant0` was incorrect for samples of size n = 2 (if the data were sorted in descending order).

The new package version (tagged `v0.5-2`) fixes the issue. I will upload the new version to [CRAN](https://cran.r-project.org/package=robsurvey) in the near future. If you need the updated version now, I recommend building the package from GitHub.

Thanks, Ryota Suzuki!

**Comment by r-suzuki** [comment]
Great, thank you!
