### ISSUE TITLE
Wrong Makefile breaks the build

### ISSUE THREAD

**Issue by barracuda156** [tobiasschoch/robsurvey#2]
Apparently that `Makefile` which breaks the build on macOS is Window-specific? Something should be done to ensure it is not used on other platforms. Otherwise this happens:
```
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-robsurvey/R-robsurvey/work/robsurvey-0.5-2" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-robsurvey/R-robsurvey/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library 
* installing *source* package ‘robsurvey’ ...
** using staged installation
** libs
gcc.exe -Wall -pedantic -Wstrict-prototypes -I C:/"Program Files"/R/R-4.2.2/include -c -o wquantile.o wquantile.c -std=gnu99 -O3
/bin/sh: gcc.exe: command not found
make: *** [wquantile.o] Error 127
ERROR: compilation failed for package ‘robsurvey’
```

**Comment by tobiasschoch** [comment]
Thanks for pointing this out, Sergey! Actually, the file `Makefile` should be ignored (because it is declared in `.Rbuildignore` and `.Rinstignore`). It seems to work on CRAN; see here: [checks](https://cran.r-project.org/web/checks/check_results_robsurvey.html)

I have to investigate this issue in more detail. Can you tell me more about the issue? Did you run `R CMD INSTALL` or `R CMD build`? 

For the moment, please install the package from CRAN.

**Comment by barracuda156** [comment]
We run it like `sudo port install R-robsurvey`: https://ports.macports.org/port/R-robsurvey
I added a patch in Macports to trash the makefile, but perhaps it is still worth fixing here, since not everyone uses Macports; as for installing pre-built binaries – well, some people do not do this in principle, some may want to, but binaries do not exist (CRAN does not support anything but a few latest and most popular platforms).

P. S. When running `sudo port test install R-robsurvey`, makefile is in fact ignored, and build and tests run nicely. So perhaps ignore works, but only when the build system copies files into a check directory. Otherwise makefile is picked and breaks everything. In any case, this is a solvable problem – usually Windows-specific build files have appropriate extensions or otherwise configure script is provided to make the correct choice.

**Comment by tobiasschoch** [comment]
I have renamed `Makefile` to `my_makefile`. The new file should not confuse the compiler.

**Comment by barracuda156** [comment]
@tobiasschoch Thank you!
